kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-hotreload
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - args:
        - --volume-dir=/etc/nginx
        - --webhook-url=http://127.0.0.1:80/-/reload
        image: jimmidyson/configmap-reload:v0.2.2
        imagePullPolicy: IfNotPresent
        name: nginx-config-configmap-reload
        volumeMounts:
        - mountPath: /etc/nginx
          name: config-volume
          readOnly: true
      - args:
        image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - mountPath: /etc/nginx
          name: config-volume
      volumes:
      - configMap:
          defaultMode: 420
          name: nginx-config
        name: config-volume
